MOCK_METRICS = {
    "overview": {
        "followers": 6240,
        "follower_growth_pct": 14.2,
        "avg_views": 18400,
        "avg_likes": 1230,
        "avg_comments": 87,
        "avg_shares": 143,
        "engagement_rate": 7.8,
    },
    "posts": [
        {
            "title": "Thrift Flip – $8 jacket to runway look",
            "platform": "TikTok",
            "views": 42000,
            "likes": 3100,
            "comments": 214,
            "shares": 480,
            "posted": "Mon 7PM",
            "pillar": "Thrift & Flip",
        },
        {
            "title": "Queens street style – Astoria edition",
            "platform": "TikTok",
            "views": 28000,
            "likes": 1900,
            "comments": 156,
            "shares": 310,
            "posted": "Wed 8PM",
            "pillar": "Queens Street Style",
        },
        {
            "title": "GRWM for a date on a budget",
            "platform": "Instagram",
            "views": 11000,
            "likes": 890,
            "comments": 63,
            "shares": 92,
            "posted": "Tue 7PM",
            "pillar": "GRWM",
        },
        {
            "title": "Culture & style – what I wear to church",
            "platform": "Instagram",
            "views": 9400,
            "likes": 720,
            "comments": 48,
            "shares": 67,
            "posted": "Thu 8PM",
            "pillar": "Culture & Style",
        },
    ],
    "top_pillar": "Thrift & Flip",
    "best_time": "Monday 7PM EST",
    "weekly_growth": [80, 120, 145, 210, 180, 240, 310],
}
